Support for Unity quota management
emc-openstack/storops pull request #344
Opened 2021-04-22 12:44 UTC by rajendraindukuri

This PR covers support for Unity Quota management:
1. CRUD operations (whichever supported by API) for userQuota, treeQuota ,quotaConfig components
2. Unit test coverage for the same

2021-04-23 14:03 UTC, yong-huang requested changes

2021-04-23 14:03 UTC, yong-huang commented on storops_test/unity/resource/test_system.py
> +                                  filesystem_id='fs_99',
Indentation

2021-04-23 14:03 UTC, yong-huang commented on storops_test/unity/resource/test_system.py
> +                                    filesystem_id='fs_2',
Indentation

2021-04-23 14:03 UTC, yong-huang commented on storops_test/unity/resource/test_system.py
> +                                  filesystem_id='fs_2',
Indentation

2021-04-23 14:03 UTC, yong-huang commented on storops_test/unity/resource/test_system.py
> +                                  filesystem_id='fs_99',
Indentation

2021-04-23 14:03 UTC, yong-huang commented on storops_test/unity/resource/test_system.py
> +                                      quota_config_id='abc',
Indentation

2021-04-24 05:14 UTC, rajendraindukuri commented on storops_test/unity/rest_data/quotaConfig/quota_config_not_found.json
> +    "existed": false,
This is a storops response.

2021-04-24 05:15 UTC, rajendraindukuri commented on storops_test/unity/rest_data/treeQuota/tree_quota_not_found.json
> +    "existed": false,
This is a storops response

2021-04-24 05:15 UTC, rajendraindukuri commented on storops_test/unity/rest_data/userQuota/user_quota_not_found.json
> +    "existed": false,
This is a storops response

2021-04-24 05:15 UTC, rajendraindukuri commented on storops_test/unity/resource/test_user_quota.py
> +        assert_that(f, raises(UnityResourceNotFoundError))
Ya @yong-huang . Just reused the existing filesystem rest data

2021-04-24 06:22 UTC, rajendraindukuri commented on storops/unity/resource/tree_quota.py
> +            allow_empty=False,
Hi @yong-huang , For now removed this attribute as by default it is false and tested all the scenarios.. it looks fine. But I did not fully understand the significance of this attribute, if you can help me with understanding the same I will try to use it accordingly. Thanks.

Same for all the similar comments

2021-04-28 08:32 UTC, yong-huang commented on storops/unity/resource/tree_quota.py
> +            allow_empty=False,
It ok if all tests passed. It only impacts the empty list/dict in the parameters.

2021-04-28 08:40 UTC, yong-huang approved these changes

2021-04-29 02:23 UTC, merged